name: pikaday_datepicker_angular
description: Provides a datepicker for Angular4 component which wrapps the lightweight pikaday js-library.
version: 4.0.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+9
  js: ^0.6.1
  pikaday: "^1.2.0"

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
### (default) configuration if this package should be used as a library (import) or if the app should be execute as Dart in Dartium
- angular
### configuration if example web folder should be compiled to js
#- angular:
#    entry_points: web/main.dart
#- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc