name: pikaday_datepicker_angular
description: Provides a datepicker for Angular4 component which wrapps the lightweight pikaday js-library.
version: 4.0.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+9
  js: ^0.6.1
  pikaday: "^1.2.0"

dev_dependencies:
  build: '>=0.11.1 <0.13.0'
  build_runner: ^0.8.1
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.5
  sass_builder: ^1.1.5