name: pikaday_datepicker_angular
description: Provides a datepicker for Angular4 component which wrapps the lightweight pikaday js-library.
version: 4.0.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular

environment:
  sdk: '>=2.0.0-dev.65.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  js: ^0.6.1
  pikaday: "^1.2.0"

dev_dependencies:
  build: '>=0.11.1 <1.0.0'
  build_runner: '>=0.8.0 <1.0.0'
  build_test: '>=0.10.0 <1.0.0'
  build_web_compilers: '>=0.4.0 <1.0.0'
  sass_builder: ^2.0.1